package lab6;


public class AdvancedWeek {
    

private final String day_1 = "Monday";
private final int day_1_index = 1;
private final String day_2 = "Tuesday";
private final int day_2_index = 2;
private final String day_3 = "Wednesday";
private final int day_3_index = 3;
private final String day_4 = "Thursday";
private final int day_4_index = 4;
private final String day_5 = "Friday";
private final int day_5_index = 5;
private final String day_6 = "Saturday";
private final int day_6_index = 6;
private final String day_7 = "Sunday";
private final int day_7_index = 7;

    
public void printdays(){
    System.out.println( day_1_index + ": " + day_1 + ",\n" +day_2_index + ": " + day_2 + ",\n" +day_3_index + ": " + day_3 + ",\n" +day_4_index + ": " + day_4 + ",\n" +day_5_index + ": " + day_5 + ",\n" +day_6_index + ": " + day_6 + ",\n" +day_7_index + ": " + day_7 + ".");

}
}

