package lab6;


public class BasicWeek {
    private final String day_1 = "Monday";
    
    private final String day_2 = "Tuesday";
    private final String day_3 = "Wednesday";
    private final String day_4 = "Thursday";
    private final String day_5 = "Friday";
    private final String day_6 = "Saturday";
    private final String day_7 = "Sunday";
    public void printdays(){
    System.out.println( day_1 + " " + day_2 + " " + day_3 + " " +day_4 + " " + day_5 + " " + day_6 + " " + day_7 );
   
    }
 
}
